language: python

python: 3.7

install:
- pip install -r requirements.txt

script:
- pytest
-
deploy:
  api_key:
    secure: lVYN8N9RVL3+puPNQnDZCjUzid+2aHsSNYdPwuxe471DTATS0s0LsS5ZfJRxF/Nb7mrlEbwEX9X4K1aQIny8dT7TS+lATdx0o7r5EuLfO2HFc2rcEzWgADqmsRqQSiH5+N6ORIjXI31F34GAB6i912xGf+3QKiTmm4zQ77OX/bd5ZymX74KP5dtuPwVkv1QYHqlCdDmLCqvpFlokZ+npO4H7gczKU/f5ezuagptoI6gPmgVsxdb7AP1jFccVmwrKJ6FVJdsKFYS+gn7XLmzKShpGXJFMuWCouHEoX94J1pTSZsatSQPSJex6/9yJPubleiV/o2FKf3Yd4LGlFPFjxGa5TGUsE6I1uMO5RgEaQ7FVMNqYB3ogakqIss+2SfTushRidP0q7liAKI9V1cuo844JxeXdjCPnGNfcmxZTOjLy0RBeqd6sa0VtHu/yq9iWMMS5lfZzq15zeA60nxDZxphVUXDot9/ZQ/jKlPc2Sadta9qfQAC1NHTRQ6M9I3gp/lkSlyxpItWoYH0WINjJ+WS1iaX2fafUseAsBNdvrRT0Jf9F38uNbIiyPqvMk5ABeEIFxbgw0kVhIaKo0Whah4s2iBJCVVa9FDcYU/c0ObU8fhAp/3RNwsrISQ3G4qVMNgsdUx3B68D2rAhGnHPOoV0eSywlmRarhj5sQ0c1I2M=
