"""removed alias unique constraint

Revision ID: f2fcd209f017
Revises: a7a42978abff
Create Date: 2019-10-02 20:15:41.625632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2fcd209f017'
down_revision = 'a7a42978abff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_alias_name', table_name='alias')
    op.create_index(op.f('ix_alias_name'), 'alias', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alias_name'), table_name='alias')
    op.create_index('ix_alias_name', 'alias', ['name'], unique=True)
    # ### end Alembic commands ###
